# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Matthieu Moquet (@MattKetmo) - Personal pages
author: Matthieu Moquet
email: matthieu@moquet.net
url: http://moquet.net
twitter_account: MattKetmo
