title: Matthieu Moquet (@MattKetmo) - Personal Pages
description: |
  Hello. My name is Matthieu Moquet (@MattKetmo).
  I currently live in Paris and work as a web engineer at BlaBlaCar
url: https://moquet.net
author: Matthieu Moquet
email: matthieu@moquet.net
twitter: MattKetmo
